/** 9 Turnbull Court PMO — Gmail, Drive and OpenAI automation. */
const SHEETS={CONFIG:'⚙️ CONFIG',SETUP:'🤖 AUTOMATION_SETUP',IMPORT:'📥 GMAIL_IMPORT',DOCS:'📚 DOCUMENT_REGISTER',INVOICES:'🧾 INVOICES',RFIS:'📝 RFI_REGISTER',PERMITS:'📜 PERMITS_APPROVALS',PROCUREMENT:'🛒 PROCUREMENT',VARIATIONS:'⚡ VARIATIONS'};
const COL={PROCESS:1,GMAIL_ID:2,THREAD_ID:3,RECEIVED:4,FROM:5,TO:6,SUBJECT:7,SNIPPET:8,CATEGORY:9,COMPANY:10,ATTACHMENT:11,MIME:12,SIZE_KB:13,REVISION:14,INVOICE_NO:15,AMOUNT:16,DUE_DATE:17,RFI_NO:18,DRAWING_NO:19,STATUS:20,DRIVE_FOLDER:21,DRIVE_URL:22,TARGET:23,REGISTER_ROW:24,IMPORTED_AT:25,HASH:26,DUPLICATE:27,NOTES:28,PROJECT:29};
const AI={URL:'https://api.openai.com/v1/responses',KEY:'OPENAI_API_KEY',ENABLED:'OPENAI_ENABLED',MODEL:'OPENAI_MODEL',DEFAULT_MODEL:'gpt-5-mini',MAX_CHARS:12000,RETRIES:3};

function onOpen(){const ui=SpreadsheetApp.getUi();ui.createMenu('9TC PMO').addItem('Run Gmail Import Now','runGmailImport').addItem('Route Ready Items','routeReadyItems').addSeparator().addSubMenu(ui.createMenu('OpenAI').addItem('Set / Replace API Key','setOpenAIApiKey').addItem('Test OpenAI Connection','testOpenAIConnection').addItem('Set AI Model','setOpenAIModel').addItem('Show AI Status','showOpenAIStatus').addItem('Enable AI Classification','enableOpenAIClassification').addItem('Disable AI Classification','disableOpenAIClassification').addItem('Clear API Key','clearOpenAIApiKey')).addSeparator().addItem('Install / Repair Trigger','setupGmailAutomation').addItem('Remove Automation Trigger','removeGmailAutomation').addToUi();}
function setupGmailAutomation(){removeGmailAutomation();ScriptApp.newTrigger('runGmailImport').timeBased().everyMinutes(15).create();getOrCreateLabel_(getSettings_().processedLabel);updateConfigStatus_('Active — 15 minute Gmail trigger installed');SpreadsheetApp.getUi().alert('Automation installed. Run Gmail Import Now for commissioning.');}
function removeGmailAutomation(){ScriptApp.getProjectTriggers().filter(t=>t.getHandlerFunction()==='runGmailImport').forEach(t=>ScriptApp.deleteTrigger(t));updateConfigStatus_('Inactive — no Gmail trigger');}

function runGmailImport(){const lock=LockService.getScriptLock();if(!lock.tryLock(1000))return;try{const s=getSettings_();validateSettings_(s);const sh=SpreadsheetApp.getActive().getSheetByName(SHEETS.IMPORT);const label=getOrCreateLabel_(s.processedLabel);const threads=GmailApp.search(s.searchQuery+' newer_than:'+s.lookbackDays+'d',0,s.maxThreads);const hashes=getKnownHashes_(sh);const root=DriveApp.getFolderById(s.rootFolderId);const rows=[];threads.forEach(thread=>{thread.getMessages().forEach(msg=>{msg.getAttachments({includeInlineImages:false,includeAttachments:true}).forEach(att=>{const hash=Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,att.getBytes()));const duplicate=hashes.has(hash);const p=classifyDocument_(msg,att);let folder='',url='',status=duplicate?'Duplicate':(s.autoRoute?'Ready':'New');let note=duplicate?'Attachment hash already exists in the import queue.':(p.aiRationale||'');if(!duplicate){const f=getOrCreateSubfolder_(root,p.category);folder=f.getName();url=f.createFile(att.copyBlob()).setName(buildFileName_(msg.getDate(),p,att.getName())).getUrl();hashes.add(hash);}rows.push([s.autoRoute&&!duplicate?'Yes':'No',msg.getId(),thread.getId(),msg.getDate(),msg.getFrom(),msg.getTo(),msg.getSubject(),cleanText_(msg.getPlainBody()).slice(0,500),p.category,p.company,att.getName(),att.getContentType(),Math.round(att.getSize()/1024),p.revision,p.invoiceNo,p.amount,p.dueDate,p.rfiNo,p.drawingNo,status,folder,url,p.targetRegister,'','',hash,duplicate?'Yes':'No',note,'9 Turnbull Court']);});});thread.addLabel(label);});if(rows.length){const r=Math.max(sh.getLastRow()+1,5);sh.getRange(r,1,rows.length,29).setValues(rows);sh.getRange(r,4,rows.length,1).setNumberFormat('dd/mm/yyyy hh:mm');sh.getRange(r,16,rows.length,1).setNumberFormat('$#,##0.00');sh.getRange(r,17,rows.length,1).setNumberFormat('dd/mm/yyyy');}if(s.autoRoute)routeReadyItems();stampLastRun_('Success — '+rows.length+' attachment(s) scanned');}catch(e){stampLastRun_('Error — '+e.message);throw e;}finally{lock.releaseLock();}}

function routeReadyItems(){const ss=SpreadsheetApp.getActive(),sh=ss.getSheetByName(SHEETS.IMPORT),last=sh.getLastRow();if(last<5)return;sh.getRange(5,1,last-4,29).getValues().forEach((row,i)=>{if(String(row[0]).toLowerCase()!=='yes'||!['Ready','New'].includes(String(row[19])))return;try{const category=row[8];let result={register:SHEETS.DOCS,row:appendDocument_(row)};if(category==='Invoice')result={register:SHEETS.INVOICES,row:appendInvoice_(row)};else if(category==='RFI')result={register:SHEETS.RFIS,row:appendRfi_(row)};else if(category==='Permit / Approval')result={register:SHEETS.PERMITS,row:appendGeneric_(SHEETS.PERMITS,row)};else if(category==='Quote / Procurement')result={register:SHEETS.PROCUREMENT,row:appendGeneric_(SHEETS.PROCUREMENT,row)};else if(category==='Variation')result={register:SHEETS.VARIATIONS,row:appendGeneric_(SHEETS.VARIATIONS,row)};sh.getRange(i+5,20).setValue('Imported');sh.getRange(i+5,23).setValue(result.register);sh.getRange(i+5,24).setValue(result.row);sh.getRange(i+5,25).setValue(new Date());sh.getRange(i+5,28).setValue('');}catch(e){sh.getRange(i+5,20).setValue('Error');sh.getRange(i+5,28).setValue(e.message);}});}
function appendDocument_(r){const sh=SpreadsheetApp.getActive().getSheetByName(SHEETS.DOCS),n=nextDataRow_(sh,5),id='DOC-'+Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyyMMdd-HHmmss')+'-'+n;sh.getRange(n,1,1,17).setValues([[id,r[3],r[8],r[9],r[10]||r[6],r[18]||r[14]||r[17],r[13],'Current',inferDiscipline_(r[6]+' '+r[10]),r[17]||r[14],r[21],r[1],'','Yes',new Date(),r[6],'9 Turnbull Court']]);return n;}
function appendInvoice_(r){const sh=SpreadsheetApp.getActive().getSheetByName(SHEETS.INVOICES),n=nextDataRow_(sh,5),amount=Number(r[15])||0,ex=amount?amount/1.1:0;sh.getRange(n,1,1,17).setValues([[r[14]||'TBC',r[3],r[9]||'Other','Both',amount,ex/2,ex/2,'No','No','No',amount,'Current','',r[6]+' | '+r[21],'','Imported','⚠ Review']]);return n;}
function appendRfi_(r){const sh=SpreadsheetApp.getActive().getSheetByName(SHEETS.RFIS),n=nextDataRow_(sh,5);sh.getRange(n,1,1,12).setValues([[r[17]||nextRfiNo_(sh),r[3],r[9]||'Email import','',r[6],'Medium','','Open','','Imported from Gmail: '+r[21],r[18],'']]);return n;}
function appendGeneric_(name,r){const sh=SpreadsheetApp.getActive().getSheetByName(name),n=nextDataRow_(sh,5),w=Math.min(sh.getLastColumn(),10),v=new Array(w).fill('');v[0]=r[6];if(w>1)v[1]=r[9];if(w>2)v[2]=r[3];if(w>3)v[3]=r[21];sh.getRange(n,1,1,w).setValues([v]);return n;}

function classifyDocument_(m,a){const fallback=ruleBasedClassify_(m,a);if(!isAIEnabled_())return fallback;try{return mergeClassification_(fallback,classifyWithOpenAI_(m,a));}catch(e){console.warn('AI fallback: '+e.message);return fallback;}}
function classifyWithOpenAI_(m,a){const text=['Subject: '+m.getSubject(),'From: '+m.getFrom(),'Attachment: '+a.getName(),'MIME: '+a.getContentType(),'Body: '+cleanText_(m.getPlainBody())].join('\n').slice(0,AI.MAX_CHARS);const schema={type:'object',additionalProperties:false,properties:{category:{type:'string',enum:['Invoice','RFI','Variation','Progress Claim','Permit / Approval','Quote / Procurement','Safety / SWMS','Inspection / QA','Contract / Subcontract','Site Report','Engineering','Drawing / Plan','Authority','Correspondence','Other']},company:{type:'string'},revision:{type:'string'},invoiceNo:{type:'string'},rfiNo:{type:'string'},drawingNo:{type:'string'},amount:{type:['number','null']},dueDate:{type:['string','null']},confidence:{type:'number',minimum:0,maximum:1},rationale:{type:'string'}},required:['category','company','revision','invoiceNo','rfiNo','drawingNo','amount','dueDate','confidence','rationale']};const response=callOpenAI_({model:getAIModel_(),store:false,max_output_tokens:1200,input:[{role:'system',content:[{type:'input_text',text:'Classify and extract metadata for an Australian residential construction PMO document. Return only the schema. Dates use YYYY-MM-DD. Amount is total AUD including GST when identifiable.'}]},{role:'user',content:[{type:'input_text',text:text}]}],text:{format:{type:'json_schema',name:'pmo_document',strict:true,schema:schema}}});const p=JSON.parse(extractOpenAIText_(response));p.targetRegister=targetRegister_(p.category);p.dueDate=p.dueDate?parseIsoDate_(p.dueDate):'';p.amount=p.amount===null?'':p.amount;return p;}
function callOpenAI_(payload){const key=PropertiesService.getScriptProperties().getProperty(AI.KEY);if(!key)throw new Error('OpenAI API key is not configured.');let last;for(let i=0;i<AI.RETRIES;i++){const res=UrlFetchApp.fetch(AI.URL,{method:'post',contentType:'application/json',headers:{Authorization:'Bearer '+key},payload:JSON.stringify(payload),muteHttpExceptions:true});const code=res.getResponseCode(),body=res.getContentText();let json;try{json=JSON.parse(body);}catch(e){throw new Error('OpenAI returned non-JSON HTTP '+code);}if(code>=200&&code<300)return json;last=new Error('OpenAI HTTP '+code+': '+((json.error&&json.error.message)||body.slice(0,300)));if(![408,409,429].includes(code)&&code<500)throw last;if(i<AI.RETRIES-1)Utilities.sleep(1000*Math.pow(2,i));}throw last;}
function extractOpenAIText_(r){if(r.output_text)return r.output_text;for(const o of (r.output||[]))for(const c of (o.content||[]))if(c.type==='output_text'&&c.text)return c.text;throw new Error('OpenAI response contained no output text.');}
function mergeClassification_(f,a){const c=Number(a.confidence||0);if(c<0.55)return f;return{category:a.category||f.category,targetRegister:targetRegister_(a.category||f.category),company:a.company||f.company,revision:a.revision||f.revision,invoiceNo:a.invoiceNo||f.invoiceNo,rfiNo:a.rfiNo||f.rfiNo,drawingNo:a.drawingNo||f.drawingNo,amount:a.amount!==''&&a.amount!==null?a.amount:f.amount,dueDate:a.dueDate||f.dueDate,aiConfidence:c,aiRationale:a.rationale||''};}
function ruleBasedClassify_(m,a){const subject=m.getSubject()||'',file=a.getName()||'',text=(subject+' '+cleanText_(m.getPlainBody())+' '+file).toLowerCase();let category='Other';if(/\b(tax invoice|invoice|inv[-_ ]?\d+)\b/.test(text))category='Invoice';else if(/\b(rfi|request for information)\b/.test(text))category='RFI';else if(/\b(variation|vo[-_ ]?\d+)\b/.test(text))category='Variation';else if(/\b(progress claim|payment claim)\b/.test(text))category='Progress Claim';else if(/\b(permit|approval|certificate|occupancy|consent)\b/.test(text))category='Permit / Approval';else if(/\b(quote|quotation|tender|proposal)\b/.test(text))category='Quote / Procurement';else if(/\b(swms|safe work method|safety|incident)\b/.test(text))category='Safety / SWMS';else if(/\b(inspection|checklist|quality assurance)\b/.test(text))category='Inspection / QA';else if(/\b(contract|subcontract|agreement)\b/.test(text))category='Contract / Subcontract';else if(/\b(site report|site diary|daily report)\b/.test(text))category='Site Report';else if(/\b(engineer|engineering|structural|civil|hydraulic)\b/.test(text))category='Engineering';else if(/\b(drawing|plan|revision|ifc|architectural)\b/.test(text))category='Drawing / Plan';else if(/\b(council|authority|water|energy|nbn|surveying)\b/.test(text))category='Authority';else if(!a.getContentType().includes('image'))category='Correspondence';return{category:category,targetRegister:targetRegister_(category),company:parseCompany_(m.getFrom()),revision:matchFirst_(file+' '+subject,/\b(?:rev(?:ision)?[ ._-]*)([a-z0-9]+)\b/i),invoiceNo:matchFirst_(text,/\b(?:invoice|inv)[ #:._-]*([a-z0-9-]+)\b/i),rfiNo:matchFirst_(text,/\brfi[ #:._-]*([a-z0-9-]+)\b/i,'RFI-'),drawingNo:matchFirst_(file+' '+subject,/\b([a-z]{1,5}[-_]\d{2,5}(?:[-_][a-z0-9]+)?)\b/i),amount:parseAmount_(text),dueDate:parseDueDate_(text)};}
function targetRegister_(c){return({Invoice:SHEETS.INVOICES,RFI:SHEETS.RFIS,Variation:SHEETS.VARIATIONS,'Progress Claim':'🏗️ PROGRESS_CLAIMS','Permit / Approval':SHEETS.PERMITS,'Quote / Procurement':SHEETS.PROCUREMENT})[c]||SHEETS.DOCS;}

function setOpenAIApiKey(){const ui=SpreadsheetApp.getUi(),r=ui.prompt('OpenAI API key','Paste the project API key. It will be stored in Script Properties, not the workbook.',ui.ButtonSet.OK_CANCEL);if(r.getSelectedButton()!==ui.Button.OK)return;const key=r.getResponseText().trim();if(!key)throw new Error('No API key supplied.');PropertiesService.getScriptProperties().setProperty(AI.KEY,key).setProperty(AI.ENABLED,'true');ui.alert('OpenAI API key stored and AI classification enabled.');}
function clearOpenAIApiKey(){PropertiesService.getScriptProperties().deleteProperty(AI.KEY);SpreadsheetApp.getUi().alert('OpenAI API key cleared.');}
function enableOpenAIClassification(){PropertiesService.getScriptProperties().setProperty(AI.ENABLED,'true');SpreadsheetApp.getUi().alert('AI classification enabled.');}
function disableOpenAIClassification(){PropertiesService.getScriptProperties().setProperty(AI.ENABLED,'false');SpreadsheetApp.getUi().alert('AI classification disabled; local rules remain active.');}
function setOpenAIModel(){const ui=SpreadsheetApp.getUi(),r=ui.prompt('OpenAI model','Enter the model ID. Default: '+AI.DEFAULT_MODEL,ui.ButtonSet.OK_CANCEL);if(r.getSelectedButton()!==ui.Button.OK)return;PropertiesService.getScriptProperties().setProperty(AI.MODEL,r.getResponseText().trim()||AI.DEFAULT_MODEL);ui.alert('Model saved.');}
function testOpenAIConnection(){const r=callOpenAI_({model:getAIModel_(),store:false,max_output_tokens:20,input:'Reply exactly: 9TC PMO OK'});SpreadsheetApp.getUi().alert('Connection successful: '+extractOpenAIText_(r));}
function showOpenAIStatus(){const p=PropertiesService.getScriptProperties(),has=!!p.getProperty(AI.KEY);SpreadsheetApp.getUi().alert('OpenAI status','Enabled: '+isAIEnabled_()+'\nKey configured: '+has+'\nModel: '+getAIModel_(),SpreadsheetApp.getUi().ButtonSet.OK);}
function isAIEnabled_(){const p=PropertiesService.getScriptProperties();return p.getProperty(AI.ENABLED)!=='false'&&!!p.getProperty(AI.KEY);}
function getAIModel_(){return PropertiesService.getScriptProperties().getProperty(AI.MODEL)||AI.DEFAULT_MODEL;}

function getSettings_(){const sh=SpreadsheetApp.getActive().getSheetByName(SHEETS.SETUP),map=Object.fromEntries(sh.getRange('A4:B12').getValues().map(r=>[String(r[0]).trim(),r[1]]));return{searchQuery:map['Gmail search query'],processedLabel:map['Processed Gmail label']||'9TC-Imported',rootFolderId:String(map['Root Drive folder ID']||'').trim(),lookbackDays:Number(map['Lookback days'])||30,maxThreads:Number(map['Maximum threads per run'])||50,autoRoute:String(map['Auto-route to registers']).toLowerCase()==='yes'};}
function validateSettings_(s){if(!s.searchQuery)throw new Error('Gmail search query is blank.');if(!s.rootFolderId||s.rootFolderId.includes('PASTE_'))throw new Error('Enter the Root Drive folder ID in 🤖 AUTOMATION_SETUP.');}
function getKnownHashes_(sh){const set=new Set(),last=sh.getLastRow();if(last>=5)sh.getRange(5,26,last-4,1).getValues().flat().filter(String).forEach(v=>set.add(String(v)));return set;}
function getOrCreateLabel_(n){return GmailApp.getUserLabelByName(n)||GmailApp.createLabel(n);}
function getOrCreateSubfolder_(root,n){const safe=n.replace(/[\\/:*?"<>|]/g,'-'),it=root.getFoldersByName(safe);return it.hasNext()?it.next():root.createFolder(safe);}
function buildFileName_(d,p,o){const stamp=Utilities.formatDate(d,Session.getScriptTimeZone(),'yyyy-MM-dd'),m=o.match(/(\.[^.]+)$/),ext=m?m[1]:'',base=o.replace(/\.[^.]+$/,'').replace(/[\\/:*?"<>|]/g,'-').slice(0,90),rev=p.revision?'_Rev-'+p.revision:'';return[stamp,p.category,p.company,base].filter(Boolean).join('_')+rev+ext;}
function parseCompany_(f){const n=String(f).replace(/<[^>]+>/g,'').replace(/["']/g,'').trim();return n||'Unknown';}
function parseAmount_(t){const m=String(t).match(/(?:aud\s*)?\$\s*([\d,]+(?:\.\d{2})?)/gi);if(!m)return'';const n=m.map(v=>Number(v.replace(/[^\d.]/g,''))).filter(Number.isFinite);return n.length?Math.max(...n):'';}
function parseDueDate_(t){const m=String(t).match(/due(?: date)?[:\s]+(\d{1,2}[\/.-]\d{1,2}[\/.-]\d{2,4})/i);if(!m)return'';const p=m[1].split(/[\/.-]/).map(Number),y=p[2]<100?2000+p[2]:p[2];return new Date(y,p[1]-1,p[0]);}
function parseIsoDate_(v){const m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?new Date(Number(m[1]),Number(m[2])-1,Number(m[3])):'';}
function matchFirst_(t,r,p){const m=String(t).match(r);return m?(p||'')+m[1]:'';}
function inferDiscipline_(t){t=String(t).toLowerCase();if(/architect/.test(t))return'Architectural';if(/structur/.test(t))return'Structural';if(/civil|stormwater|drainage/.test(t))return'Civil';if(/hydraulic|plumb/.test(t))return'Hydraulic';if(/electrical|power/.test(t))return'Electrical';if(/landscape/.test(t))return'Landscape';if(/survey/.test(t))return'Survey';return'General';}
function nextDataRow_(s,m){return Math.max(s.getLastRow()+1,m);}
function nextRfiNo_(s){return'RFI-'+String(Math.max(s.getLastRow()-3,1)).padStart(3,'0');}
function cleanText_(t){return String(t||'').replace(/\s+/g,' ').trim();}
function stampLastRun_(s){const sh=SpreadsheetApp.getActive().getSheetByName(SHEETS.CONFIG);if(sh){sh.getRange('H10').setValue(new Date()).setNumberFormat('dd/mm/yyyy hh:mm');sh.getRange('H11').setValue(s);}}
function updateConfigStatus_(s){const sh=SpreadsheetApp.getActive().getSheetByName(SHEETS.CONFIG);if(sh)sh.getRange('B21').setValue(s);}
